/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'selector',
    content: ['./src/js/**/*.{vue,js,php}'],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
                display: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
                mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
            },
            colors: {
                primary: {
                    50:  '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#8b5cf6',
                    600: '#7c3aed',
                    700: '#6d28d9',
                    800: '#5b21b6',
                    900: '#4c1d95',
                },
                neutral: {
                    25:  '#fcfcfd',
                    50:  '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
                success: {
                    50:  '#f0fdf4',
                    100: '#dcfce7',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                },
                warning: {
                    50:  '#fffbeb',
                    100: '#fef3c7',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                },
                error: {
                    50:  '#fef2f2',
                    100: '#fee2e2',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                },
                info: {
                    50:  '#eff6ff',
                    100: '#dbeafe',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                },
                accent: {
                    purple:         '#8B5CF6',
                    'purple-dark':  '#7C3AED',
                    'purple-light': '#EDE9FE',
                    blue:           '#3B82F6',
                    'blue-light':   '#DBEAFE',
                    teal:           '#14B8A6',
                    'teal-light':   '#CCFBF1',
                    pink:           '#F472B6',
                    'pink-light':   '#FCE7F3',
                    orange:         '#F59E0B',
                    'orange-light': '#FEF3C7',
                    green:          '#22C55E',
                    'green-light':  '#DCFCE7',
                    red:            '#EF4444',
                    'red-light':    '#FEE2E2',
                },
            },
            fontSize: {
                xs:   ['0.75rem',   { lineHeight: '1rem' }],
                sm:   ['0.8125rem', { lineHeight: '1.25rem' }],
                base: ['0.875rem',  { lineHeight: '1.375rem' }],
                lg:   ['1rem',      { lineHeight: '1.5rem' }],
                xl:   ['1.125rem',  { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem',   { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem',  { lineHeight: '2.5rem' }],
            },
            borderRadius: {
                sm:   '8px',
                md:   '12px',
                lg:   '16px',
                xl:   '20px',
                '2xl': '24px',
                pill:  '100px',
            },
            boxShadow: {
                xs:   '0 1px 2px 0 rgb(0 0 0 / 0.05)',
                sm:   '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
                md:   '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
                lg:   '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
                xl:   '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
                ring: '0 0 0 3px rgb(139 92 246 / 0.15)',
            },
            transitionDuration: {
                fast:    '100ms',
                normal:  '200ms',
                slow:    '300ms',
                slower:  '500ms',
            },
            transitionTimingFunction: {
                default: 'cubic-bezier(0.4, 0, 0.2, 1)',
                spring:  'cubic-bezier(0.34, 1.56, 0.64, 1)',
            },
            animation: {
                'skeleton': 'pulse 1.5s ease-in-out infinite',
                'fade-in':  'fadeIn 200ms ease-out',
                'slide-up': 'slideUp 200ms ease-out',
                'counter':  'counter 800ms ease-out',
            },
            keyframes: {
                fadeIn: {
                    '0%':   { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%':   { opacity: '0', transform: 'translateY(8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
            },
            spacing: {
                '4.5': '1.125rem', // 18px
                '13':  '3.25rem',  // 52px
                '15':  '3.75rem',  // 60px
                '18':  '4.5rem',   // 72px
            },
            width: {
                'sidebar-expanded':  '240px',
                'sidebar-collapsed': '64px',
            },
        },
    },
    plugins: [],
}
